name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.17.0
  geolocator: ^11.0.0
  geolocator_web: ^3.0.0
  weather_icons: ^3.0.0
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Remove or comment out the assets section since we're not using it yet
  # assets:
  #   - assets/
